# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3],[4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np. array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a3.dtype, a3.size, a1.ndim, type(a1)

((3,), dtype('int32'), 12, 1, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.shape, a2.dtype, a2.size, a2.ndim, type(a2)

((2, 3), dtype('int32'), 6, 2, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape, a3.dtype, a3.size, a3.ndim, type(a3)

((2, 2, 3), dtype('int32'), 12, 3, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [7]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
arange = np.arange(0, 100, 3)
arange

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random = np.random.randint(0, 10, size=(7, 2))
random

array([[1, 4],
       [3, 2],
       [7, 2],
       [6, 9],
       [9, 9],
       [0, 0],
       [6, 0]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rfloat = np.random.random((3, 5))
rfloat

array([[0.56147816, 0.11483947, 0.4869676 , 0.41377438, 0.10900494],
       [0.01942901, 0.2218583 , 0.30504738, 0.86324287, 0.08070264],
       [0.74980234, 0.52173714, 0.74413575, 0.74840581, 0.2989902 ]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array = np.random.randint(0, 10, size=(4, 6))
random_array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_2 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(random_2)

array([1, 2, 3, 4, 5, 7, 9])

In [14]:
# Find the 0'th index of the latest array you created
random_2[0]

array([9, 1, 3, 7, 4, 9, 3])

In [15]:
# Get the first 2 rows of latest array you created
random_2[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
random_2[:2, :2]

array([[9, 1],
       [5, 3]])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_3 = np.random.randint(0, 10, size=(3, 5))
ones_3 = np.ones((3, 5))
ones_3, random_3

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5],
        [5, 9, 3, 5, 1]]))

In [18]:
# Add the two arrays together
random_3 + ones_3

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [19]:
# Create another array of ones of shape (5, 3)
random_4 = np.random.randint(0, 10, (5, 3))
random_4

array([[9, 1, 9],
       [3, 7, 6],
       [8, 7, 4],
       [1, 4, 7],
       [9, 8, 8]])

In [20]:
# Try add the array of ones and the other most recent array together
random_3 + np.reshape(random_4, (3, 5))

array([[15,  8, 11,  3, 10],
       [ 7, 15, 10,  5,  6],
       [ 9, 16, 12, 13,  9]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

reshape the variable random_4 from (5, 3) into (3, 5) b using reshape numpy

In [21]:
# Create another array of ones of shape (3, 5)
ones_5 = np.ones((3, 5))
ones_5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Subtract the new array of ones from the other most recent array
random_3 - np.reshape(random_4, (3, 5)) - ones_5

array([[-4.,  5., -8., -4., -5.],
       [-6., -2., -5., -4.,  3.],
       [ 0.,  1., -7., -4., -8.]])

In [23]:
# Multiply the ones array with the latest array
ones_5 * random_3

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [24]:
# Take the latest array to the power of 2 using '**'
random_3 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [25]:
# Do the same thing with np.square()
np.square(random_3)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [26]:
# Find the mean of the latest array using np.mean()
np.mean(random_3)

3.8666666666666667

In [27]:
# Find the maximum of the latest array using np.max()
np.max(random_3)

9

In [28]:
# Find the minimum of the latest array using np.min()
np.min(random_3)

0

In [29]:
# Find the standard deviation of the latest array
np.std(random_3)

2.578543947441829

In [30]:
# Find the variance of the latest array
np.var(random_3)

6.648888888888889

In [31]:
# Reshape the latest array to (3, 5, 1)
np.reshape(random_3, (3, 5, 1))

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [32]:
# Transpose the latest array
random_3.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

What does the transpose do?

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
int1 = np.random.randint(0, 10, (3, 3))
int2 = np.random.randint(0, 10, (3, 2))
int1, int2

(array([[0, 8, 6],
        [8, 7, 0],
        [7, 7, 2]]),
 array([[0, 7],
        [2, 2],
        [0, 4]]))

In [34]:
# Perform a dot product on the two newest arrays you created
np.dot(int1, int2)

array([[16, 40],
       [14, 70],
       [14, 71]])

In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
int3 = np.random.randint(0, 10, (4, 3))
int4 = np.random.randint(0, 10, (4, 3))
int3, int4

(array([[9, 6, 9],
        [8, 6, 8],
        [7, 1, 0],
        [6, 6, 7]]),
 array([[4, 2, 7],
        [5, 2, 0],
        [2, 4, 2],
        [0, 4, 9]]))

In [36]:
# Perform a dot product on the two newest arrays you created
np.dot(int3, int4.T) # change

array([[111,  57,  60, 105],
       [100,  52,  56,  96],
       [ 30,  37,  18,   4],
       [ 85,  42,  50,  87]])

It doesn't work. How would you fix it?

transpose the variable int4 with T

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(int3.T, int4),

(array([[ 90,  86, 131],
        [ 56,  52,  98],
        [ 76,  62, 126]]),)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
oke1 = np.random.randint(0, 10, (3, 6))
oke2 = np.random.randint(0, 10, (3, 6))

In [39]:
# Compare the two arrays with '>'
oke1 > oke2

array([[False, False,  True,  True,  True, False],
       [False, False, False,  True,  True, False],
       [False, False, False, False, False, False]])

What happens when you compare the arrays with `>`?

In [40]:
# Compare the two arrays with '>='
oke1 >= oke2

array([[False, False,  True,  True,  True, False],
       [ True, False, False,  True,  True, False],
       [False,  True, False,  True, False, False]])

In [41]:
# Find which elements of the first array are greater than 7
oke2 > 7

array([[ True,  True, False, False, False,  True],
       [False,  True, False, False, False,  True],
       [ True, False,  True, False, False, False]])

In [42]:
# Which parts of each array are equal? (try using '==')
oke1 == oke2

array([[False, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [False,  True, False,  True, False, False]])

In [43]:
# Sort one of the arrays you just created in ascending order
np.sort(oke1)

array([[2, 6, 6, 8, 9, 9],
       [0, 3, 3, 4, 6, 6],
       [1, 2, 3, 5, 6, 6]])

In [44]:
# Sort the indexes of one of the arrays you just created
np.argsort(oke1)

array([[5, 0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0, 5],
       [5, 3, 1, 4, 0, 2]], dtype=int64)

In [45]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(oke1)

3

In [46]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(oke1)

7

In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(oke1, axis=1)

array([3, 0, 0], dtype=int64)

In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(oke1, axis=0)

array([0, 1, 1, 2, 1, 2], dtype=int64)

In [49]:
# Create an array of normally distributed random numbers
normal = np.random.randn(3, 5)
normal

array([[-2.65517605,  0.34551794, -0.39551645, -0.28913686,  0.45293633],
       [-0.16606091,  0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618,  0.10234768]])

In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100
linspace = np.linspace(1, 100, 10)
linspace

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.